DROP TABLE meeting;
DROP TABLE meeting_attendees;
DROP TABLE meeting_calls;
DROP TABLE review;
DROP TABLE conflict;
DROP TABLE collaborator;
DROP TABLE proposal;
DROP TABLE grant_call;
DROP TABLE researcher;
